check50:
  checks:
    hello_wold:
      - run: python3 hello.py
        stdin: royals
        stdout: Hello, Royals!
        exit: 0
    hello_fred:
      - run: python3 hello.py
        stdin: Fred
        stdout: Hello, Fred!
        exit: 0
