check50:
  checks:
    hello_wold:
      - run: python3 hello2.py
        stdin: 
          - royals
          - 12
        stdout: Hello, Royals!
        stdout: See you in 12 mins.
        exit: 0
    hello_fred:
      - run: python3 hello.py
        stdin: Fred
        stdout: Hello, Fred!
        exit: 0
